### PR TITLE
fix effects #1016

### LINKED ISSUE #1016: after re-entering the server the effects were not sent

### PR DESCRIPTION
**Pull request by FDUTCH**
fix #1016

### CODE REVIEW

File: server/entity/effect.go [hunk 1]
```diff
@@ -59,6 +62,20 @@ func (m *EffectManager) Add(e effect.Effect, entity Living) effect.Effect {
 	return e
 }
 
+// checkInitials checks if added effect intersects with initial effects.
```
Comment (DaPigGuy) [inline server/entity/effect.go:65]: I think instead of just applying the initial effect that matches, just apply all of them

```
fn flushInitialEffects:
    initialEffects = m.initialEffects
    m.initialEffects = nil
    for every initialEffects:
        m.Add(initialEffect)
  ```

That way, we can get rid of the duplicated logic for which effect will take precedence. 
Please also use in Remove() and Tick()

File: server/entity/effect.go [hunk 2]
```diff
@@ -78,7 +95,7 @@ func (m *EffectManager) Effect(e effect.Type) (effect.Effect, bool) {
 // Effects returns a list of all effects currently present in the effect manager. This will never include
 // effects that have expired.
 func (m *EffectManager) Effects() []effect.Effect {
```
Comment (DaPigGuy) [inline server/entity/effect.go:97]: Please also fix Effect()

**Review by DaPigGuy — CHANGES_REQUESTED** [review]

File: server/entity/effect.go (hunk 1 above)
Comment (FDUTCH) [reply server/entity/effect.go]: don't really understand that: "Please also use in Remove() and Tick()"
(and the whole comment seems to be AI generated)

File: server/entity/effect.go [hunk 3]
```diff
@@ -71,14 +89,20 @@ func (m *EffectManager) Remove(e effect.Type, entity Living) {
 // Effect returns the effect instance and true if the entity has the effect. If not found, it will return an empty
 // effect instance and false.
 func (m *EffectManager) Effect(e effect.Type) (effect.Effect, bool) {
+	for _, eff := range m.initialEffects {
```
[the remark this answers is not in the document]
Comment (FDUTCH) [reply server/entity/effect.go:92]: No need cause if m.initialEffects != nil, m.effects is empty

[the remark this answers is not in the document]
Comment (DaPigGuy) [reply server/entity/effect.go:90]: Right, Add flushes initial effects now

File: server/entity/effect.go [hunk 4]
```diff
@@ -59,8 +62,21 @@ func (m *EffectManager) Add(e effect.Effect, entity Living) effect.Effect {
...
+	initialEffects := m.initialEffects
+	m.initialEffects = nil
+	for _, e := range initialEffects {
+		m.Add(e, entity)
+	}
+}
+
 // Remove removes any Effect present in the EffectManager with the type of the effect passed.
 func (m *EffectManager) Remove(e effect.Type, entity Living) {
+	if m.initialEffects != nil {
```
Comment (DaPigGuy) [inline server/entity/effect.go:76]: Here too

File: server/entity/effect.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (FDUTCH) [reply server/entity/effect.go:90]: I can't do that, if I will than I need to pass entity in the function
