### PR TITLE
Fix splash and lingering potions and bottle o' enchanting

### LINKED ISSUE #746: Splash and lingering potions don't behave exactly like vanilla
1. Potions travel a shorter distance in dragonfly.
2. ~~The color of the potion entity doesn't match the color of the potion you threw (e.g if you throw a fire resistance potion, it would throw a blue colored one instead of orange), though this is purely visual and it doesn't affect the type of potion thrown.~~ This seems to have been fixed
3. The effect particles color of some potions are outdated.

Dragonfly version: 0.9.20
Minecraft version: 1.21.50

~~Here's a video showcasing the issue
https://streamable.com/7h9qlt~~

### PR DESCRIPTION
**Pull request by mmm545**
This PR aims to fix #746

### CODE REVIEW

File: server/item/bottle_of_enchanting.go [hunk 1]
```diff
@@ -11,7 +11,9 @@ type BottleOfEnchanting struct{}
 // Use ...
 func (b BottleOfEnchanting) Use(tx *world.Tx, user User, ctx *UseContext) bool {
 	create := tx.World().EntityRegistry().Config().BottleOfEnchanting
-	opts := world.EntitySpawnOpts{Position: eyePosition(user), Velocity: user.Rotation().Vec3().Mul(0.7)}
+	r := user.Rotation()
+	r[1] = throwableOffset(r[1])
+	opts := world.EntitySpawnOpts{Position: eyePosition(user), Velocity: r.Vec3().Mul(0.6)}
```
Comment (mmm545) [inline server/item/bottle_of_enchanting.go:16]: This is not a mistake by the way. For some reason, bottle o' enchanting needed a higher throwing force (`0.6`) than splash and lingering potions (`0.5`) to match vanilla.

**Review by Sandertv — APPROVED** [review]
Looks good, thank you for the PR!
